### ISSUE TITLE
replace in line code on wiki with a link to here?

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#10]
I suggest the [shell script posted on the wiki](http://wiki.octave.org/Create_a_MacOS_X_App_Bundle_Using_Homebrew) be replaced by a link to the git repository.

**Comment by schoeps** [comment]
Agreed. I have updated the wiki and I will add links to recent gui and cli app bundles later. What do you think, shall we replace or merge the old mac wiki pages? (it's quite a mess...)

**Comment by bpabbott** [comment]
Perhaps a simple rewrite of [Octave_for_MacOS_X#Installing_a_Mac_OS_X_Bundle](http://wiki.octave.org/Octave_for_MacOS_X#Installing_a_Mac_OS_X_Bundle). I can take care of that and will leave changes to the [Create_a_MacOS_X_App_Bundle_Using_Homebrew](http://wiki.octave.org/Create_a_MacOS_X_App_Bundle_Using_Homebrew) page in your hands.

Beyond that, let's discuss major changes on the maintainers mail-list prior to proceeding.
