### ISSUE TITLE
gl2ps?

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#11]
Is gl2ps included in the Homebrew app. I don't see it being installed in the script, but it is installed via Fink on both my computers.

**Comment by schoeps** [comment]
gl2ps is included in line 95, see https://github.com/Homebrew/homebrew-science/blob/master/octave.rb

**Comment by bpabbott** [comment]
Ok. I'm still used to conventional package manages where gl2ps would be packaged independently.
Thanks

**Comment by schoeps** [comment]
It's independent and installed in `.../opt/gl2ps`, see https://github.com/Homebrew/homebrew-core/blob/master/Formula/gl2ps.rb
