### ISSUE TITLE
Dock Icon

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#12]
The icon on the dock remains a black box with "exec" inside, [exec].

I'm able to fix that by

(1) Right click on dock icon (labeled "exec")
(2) Get-Info on the octave-gui executable
(3) Copy the applet.icns in the Resources directory
(4) Click on "exec" icon for octave-gum seen in the Get-Info window and paste applet.icns

I assume there is a way to automate this, but I don't know how

**Comment by schoeps** [comment]
This [python](http://superuser.com/questions/133784/manipulate-mac-os-x-file-icons-from-automator-or-command-line) script can do it

```
#!/usr/bin/env python
import Cocoa
import sys

Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_(sys.argv[1].decode('utf-8')), sys.argv[2].decode('utf-8'), 0) or sys.exit("Unable to set file icon")
```

I will include it in the installer...
