### ISSUE TITLE
Transfig

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#13]
I noticed the error below while running the script.

```
Error: Formulae found in multiple taps: 
 * homebrew/science/transfig
 * schoeps/xfig/transfig
```

**Comment by schoeps** [comment]
transfig (fig2dev) was added to homebrew science, therefore my private repository is not necessary anymore.  For new users this is already fixed by 46f51cd475fa9c1c719a6607c73e4c9d94a55356. 

You might need to do the following:
```
cd /Applications/Octave.app/Contents/Resources/usr/
./brew uninstall transfig
./brew untap schoeps/xfig
```

**Comment by bpabbott** [comment]
Thanks. I'm having other problems when updating (ex: octave isn't being built). So I've deleted Octave.app. Perhaps the script should be modified so that it terminates when an error occurs?

**Comment by schoeps** [comment]
Agreed. I think that you already invoke the script with switch `-e`, e.g.

`bash -e install_octave.sh`

**Comment by bpabbott** [comment]
Ok. I knew the first line could be changed to be

`#!/bin/sh -e`

But I didn't know of your suggestion. Thanks
