### ISSUE TITLE
Crash related to veclib?

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#16]
I'm attaching a crash log that looks to indicate vecLib is being linked to.

[octave-gui.txt](https://github.com/schoeps/octave_installer/files/282993/octave-gui.txt)

**Comment by schoeps** [comment]
True, but that might be because some dependency, possibly from apple is linking to veclib. I am only enforcing openblas for libraries that are known to be critical. For example fftw might be build based on veclib. Do you think that this is a problem?

**Comment by bpabbott** [comment]
I'm not certain, what happens with Apple's toolchain. If `fftw` is the only concern, then I think we can try building without it. I can just add `--without-fftw` to `octave-settings` correct?

**Comment by bpabbott** [comment]
I encountered the same crash when building with `--without-fftw`. I'll need to investigate further using `otool` and verify that the `vecLib` framework is actually being linked to.

**Comment by bpabbott** [comment]
I wrote a recursive search of all libraries. The only libraries that link to `vecLib` are Apple's. The crash must be due to some other problem.

**Comment by schoeps** [comment]
Can you explain/reproduce when octave crashes?

**Comment by bpabbott** [comment]
I'd been meaning to try to track down the problem, but keep forgetting. Turns out it is very easy to find where the crash occurs. I just looked over the terminal output and found the problem is with HD5.

```
  io.tst ......................................................Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.16, library is 1.8.14
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
		   HDF5 Version: 1.8.14
		  Configured on: Tue Jan 13 07:47:08 CET 2015
		  Configured by: hecht@MBP-FH.local
		 Configure mode: production
		    Host system: i386-apple-darwin14.0.0
	      Uname information: Darwin MBP-FH.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
		       Byte sex: little-endian
		      Libraries: static, shared
	     Installation point: /usr/local

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /usr/bin/clang ( Apple LLVM version 6.0 )
                         CFLAGS: 
                      H5_CFLAGS:  -O3
                      AM_CFLAGS: 
                       CPPFLAGS: 
                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS: 
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/usr/local/lib
 	 	Extra libraries:  -lz -ldl -lm 
 		       Archiver: ar
 		 	 Ranlib: ran lib
 	      Debugged Packages: 
		    API Tracing: no

Languages:
----------
                        Fortran: no

                            C++: yes
                   C++ Compiler: /usr/bin/clang++ ( Apple LLVM version 6.0 )
                      C++ Flags: 
                   H5 C++ Flags:  -O3
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

Features:
---------
                  Parallel HDF5: no
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v18
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(lib)

         I/O filters (internal): shuffle,fletcher32,bit,scaleoffset
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
       Large File Support (LFS): yes
Bye...
panic: Abort trap: 6 -- stopping myself...
octave exited with signal 6
```

**Comment by bpabbott** [comment]
I've confirmed that `test io.txt` reliably crashes the Octave app.

I'm able to run `test io.tst` using my Fink build of 4.0.1. So I used `otool -L` to recursively look through all the libs being linked to and found `/usr/local/lib/libhdf5.9.dylib` which was likely installed without my knowledge by an application which probably has an icon in `/Applications`, but is not a self contained bundle (very annoying). It is likely FreeFem++. I've tried removing all suspicious content under `/usr/local`. No doubt some apps that violate my sensibilities are now broken.

In any event, I'll start fresh install and report back tomorrow.

Is there a way to make sure Homebrew doesn't use anything in `/usr/local`?

**Comment by bpabbott** [comment]
I took at look at the output of `./configure --help`, and see that the include and lib directories can be specified for hdf5.
```
  --with-hdf5-includedir=DIR
                          look for HDF5 include files in DIR
  --with-hdf5-libdir=DIR  look for HDF5 libraries in DIR
```
The change below should work, correct?
```
octave_settings="--with-hdf5-includedir=$install_dir/Contents/Resources/usr/include $octave_settings"
octave_settings="--with-hdf5-libdir=$install_dir/Contents/Resources/usr/lib $octave_settings"

```

**Comment by schoeps** [comment]
I am afraid your approach will not work. However, I already made an update to `octave.rb`, see https://github.com/schoeps/homebrew-science/commit/c3ac2148c138509e0ba5ac8488f6a4f6185c95cf.

If it fixes your problem, I will submit it to homebrew soon. For now, you can already test it by adding these lines to `install_octave.sh` before actually brewing octave. They manually replace `octave.rb` by the most recent one from my repository
```
# get newest octave formula and then build octave
curl https://raw.githubusercontent.com/schoeps/homebrew-science/octave/octave.rb -o "$install_dir/Contents/Resources/usr/Library/Taps/homebrew/homebrew-science/octave.rb"
```

**Comment by bpabbott** [comment]
Your solution worked for me. Thanks.

**Comment by bpabbott** [comment]
`make check` ran fine with your change, but the gui doesn't launch when I double-click on the app. 

However, Octave does launch when I enter `/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/octave` from the Terminal.

I'll try another fresh install.

**Comment by schoeps** [comment]
I just made a pull request at homebrew-science, i.e., this changeset should be added soon... 
https://github.com/Homebrew/homebrew-science/pull/3700

**Comment by bpabbott** [comment]
I've confirmed that double-clicking on the app no longer works. Also the icon in the Applications folder is the default icon again. Can you try a fresh install and confirm?

**Comment by schoeps** [comment]
Strange, I just rebuild Octave from scratch and it worked fine.

**Comment by bpabbott** [comment]
I found the problem. I first confirmed that a working app is produced without `-e`. And then started debugging. The `grep` for `oct_ver` as the source of the problem. 

```
@@ -99,10 +103,10 @@ if [ "$build_gui" == "y" ]; then
 fi
 
 # finally build octave
-./brew install octave $octave_settings
+./brew install octave $octave_settings --without-test
 
 # get versions
-oct_ver="$(./octave --version |sed -n 1p |grep -o '\d\..*$' )"
+oct_ver="$(./octave --version |sed -n 1p | grep -Po '\d.\d.\d$' )"
 oct_ver_string="$(./octave --version | sed -n 1p)"
 oct_copy="$(./octave --version | sed -n 2p | cut -c 15- )"
```

 I also removed `make check` from the octave install to speed up debugging. But that had nothing do with the problem.

The icon remains the default. I'll try of figure out what changed there as well.

**Comment by schoeps** [comment]
1) Shall I replace the `oct_ver` line? Why is `-P` suddenly necessary? 
2) Is your line also working for release candidates? (this is not major issue).

**Comment by bpabbott** [comment]
The '-P' shouldn't be needed. It was my shortest path to a working solution, but I don't think it is what should be used.

The syntax you used didn't look correct to me, and wasn't working. I also tried "[0-9]\..*$" but it didn't work for me, either.

**Comment by schoeps** [comment]
Pushed a new version.

**Comment by bpabbott** [comment]
After more thought it occurred to me that you were likely using `/usr/bin/grep` and I was using `/sw/bin/grep`.  When I modified `install_octave.sh` to use the system `grep`,

`octave --version |sed -n 1p | /usr/bin/grep -o '\d\..*$'
`

`oct_ver` contains the proper string.

**Comment by bpabbott** [comment]
Some examples from my Terminal session.

```
$ octave --version | sed -n 1p | grep -o '\d.\d.\d$'
$ octave --version |sed -n 1p | /usr/bin/grep -o '\d\..*$'
4.0.1
$ octave --version | sed -n 1p | /usr/bin/grep -o '\d.\d.\d$'
4.0.1
```

As you pointed out, it is preferred that the solution work release candidates. Thus, the 2nd would be preferred.

**Comment by schoeps** [comment]
Yes, this explains everything (and I should have known...). Now using the Apple (BSD) versions of the tools, see commit https://github.com/schoeps/octave_installer/commit/0f162c53b3f6e1bfc38fbbc00be9b6038b331a1a

**Comment by bpabbott** [comment]
Looks good to me. The last problem I see is that the icon I see in the Finder is the default `applt.icns`. I have `/Applications` in my Dock, and the default `applt.icns` also shows up there. When I `Show Package Contents`, the `applt.icns` file has the Octave icon associated with it. `octave-gui` also has the proper icon association. When I run Octave's gui, the proper icon does show up in the Dock.

Is the icon in `/Applications` correct for you?

I have a copy of `Octave.app` whose icons are working, but am unable to detect any difference (`info.plist` is identical except for `Bundle version strings, short`). Perhaps a copy of `octave_installer.sh` should be included in the app bundle to make debugging such problems easier.

**Comment by bpabbott** [comment]
I also checked `Get Info`. The correct icon is display there too. Something is weird. I hate the idea, but maybe I need to apply the MSFT fix and reboot :-(

**Comment by schoeps** [comment]
It's a Finder bug. Finder seems to cache icons. Just rename `Octave.app` to `Octave2.app` and back to `Octave.app`...

**Comment by bpabbott** [comment]
Ok. That worked! Thanks.
