### ISSUE TITLE
fltk & native graphics

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#19]
The comment below looks to be wrong. I'm able to build the gui without `fltk` installed and am able to plot as well (using the `qt` toolkit). What specifically is the broken when `fltk` isn't present?

```
# enforce fltk (without fltk all native graphics is disabled and
# e.g. gl2ps is not used. This will be untangled in Octave 4.2)
# we use devel because fltk 1.3.3 does not work on recent Mac OS
./brew install fltk --devel
```

**Comment by bpabbott** [comment]
When configured with `--without-fltk`, the following warnings occur. However, the warning is not correct. If the `qt` libraries are present, the native graphics remained enabled.

```
configure: WARNING: --without-fltk specified.  Native graphics will be disabled.
configure: WARNING: OSMesa library not found.  Offscreen rendering with OpenGL will be disabled.
configure: WARNING: 
configure: WARNING: I didn't find the necessary libraries to compile native
configure: WARNING: graphics.  It isn't necessary to have native graphics,
configure: WARNING: but you will need to have gnuplot installed or you won't
configure: WARNING: be able to use any of Octave's plotting commands
configure: WARNING: 
```

**Comment by schoeps** [comment]
Yes and no. The warning is misleading but still important. Yes, qt plotting (on screen) is still possible but no printing is not. Octave stops looking for `gl2ps` and `fi2dev` if `--without-fltk` was specified. I made a bug report and John rewrote the configure switches for 4.2....

**Comment by bpabbott** [comment]
Ok. I hadn't noticed `gl2ps` was disabled when `fltk` wasn't present. Thanks.
