### ISSUE TITLE
octave.icns is missing

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#2]
I've made my first attempt at using `octave_installer`, and found a problem with `octave.ins`. 

> created: /Users/bpabbott/rw.Octave-Installer.dmg
> Mounting disk image...
> Unmounting disk image...
> Mount directory: /Volumes/Octave-Installer
> Device name:     /dev/disk6
> Copying background file...
> making link to Applications dir
> /Volumes/Octave-Installer
> Copying volume icon file '/Applications/Octave.app/Contents/Resources/octave.icns'...
> cp: /Applications/Octave.app/Contents/Resources/octave.icns: No such file or directory
> DMG ready: /Users/bpabbott/Octave-Installer.dmg

**Comment by bpabbott** [comment]
The problem looks to be that `octave.svg` does not exist.

```
svg_icon="$install_dir/Contents/Resources/usr/opt/octave/share/icons/hicolor/scalable/apps/octave.svg"
```
In fact, there is no `octave` directory in `opt`.
```
$ ls $install_dir/Contents/Resources/usr/opt/octave
ls: /Applications/Octave.app/Contents/Resources/usr/opt/octave: No such file or directory

```

**Comment by schoeps** [comment]
My script does not do any error checking, so if ghostsript fails, then probably everythings else fails too :(

I just tried to reinstall ghostscript and it worked. Can try the following:
`cd /Applications/Octave.app/Contents/Resources/usr/bin/`
`./brew install ghostscript`
and report any error?

**Comment by bpabbott** [comment]
After downloading the tarballs for `ghostscript` and `octave` manually, the script completed. The app runs for me as well.

**Comment by schoeps** [comment]
hurrah!  We have an app :-) I am surprised that the downloads failed but this might should have nothing to do with octave....

**Comment by schoeps** [comment]
Can I close this issue?

**Comment by bpabbott** [comment]
Yes. Please close. I tried to do that myself, but I don't appear to be allowed.
