### ISSUE TITLE
demo splinefit

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#23]
Running `demo spline fit` causes the app to hang. I built the app on Mac OS 10.11.

**Comment by bpabbott** [comment]
Opps. I spoke too soon. After hanging for a few minutes, the demo ran as expected. It then runs without delay. I tried quitting and running a new session, but was unable to duplicate the hang.

**Comment by schoeps** [comment]
did you get a warning message when launching octave that plotting might be slow? (the font cache is now created in ~/.cache/fontconfig if not present. I believe this was one reason dir plotting crashes.)

**Comment by bpabbott** [comment]
I didn't notice a warning, but `~/.cache/fontconfig` does contain a few files that were generated at the time I ran the app, so perhaps I missed the warning.

**Comment by schoeps** [comment]
Can you delete (or rename) ~/.cache/fontconfig and run Octave again? - it should complain.

**Comment by bpabbott** [comment]
After deleting the font cache, I get the dialog. I definitely didn't see the dialog the first time. Maybe the folder was present, but the font's weren't all present?

**Comment by schoeps** [comment]
...or it was outdated. The existence of the directory is obviously only a necessary condition, but not sufficient :)
