### ISSUE TITLE
Linking to Metis

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#5]
`metis` is listed in the DEPENDENCIES. Linking to `metis` and then distributing the result is in violation of GPL3.

> metis
> Serial programs that partition graphs and order matrices
> http://glaros.dtc.umn.edu/gkhome/views/metis

 `metis` is a dependency of `suitesparse`. Unfortunately, the Homebrew formula does not permit `metis` to be disabled. Both [Fink](http://fink.cvs.sourceforge.net/fink/dists/10.9-libcxx/stable/main/finkinfo/sci/suitesparse.info?view=markup) and [Macports](https://trac.macports.org/browser/trunk/dports/math/SuiteSparse/Portfile) provide versions of `suitesparse` with `metis` disabled. I assume you can create a new variant of the `suitesparse` formula that disables `metis`?

**Comment by bpabbott** [comment]
I found a [patch](https://git.stoo.org/infra/nixpkgs/commit/d582090a15912b5838720a8e0a51accacf043c03?view=inline) that disables `metis` for `suitesparse` 4.4.1, which is close enough to 4.5.1 (used by Homebrew) that it should work.

**Comment by schoeps** [comment]
I think this is not necessary anymore, see http://glaros.dtc.umn.edu/gkhome/metis/metis/faq
> Can I distribute METIS with my application?
> METIS as of 5.0.3 is being distributed under the Apache License Version 2.0.

**Comment by bpabbott** [comment]
I hadn't realized that Metis is now under the Apache license. That's good news!
