### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#6]
My build is occasionally interrupted. Can the script be modified to validate the install of each dependent when it runs and install/update/upgrade dependents when needed? If the function below is added,
```
function verify_dependent
{
if ./brew list $1 ; then
  echo "$1 is installed"
else
  brew install $@
fi
}
```
Then can the update if-block can be replaced by,
```
# start compiling
./brew  tap homebrew/science
verify_dependent imagemagick --with-librsvg
verify_dependent graphicsmagick --with-quantum-depth-16
verify_dependent ghostscript
# we prefer openblas over Apple's BLAS implementation
verify_dependent arpack --with-openblas
verify_dependent qrupdate --with-openblas
verify_dependent suite-sparse --with-openblas
# install Qscintilla2 without python bindings
verify_dependent qscintilla2 --without-python
# install fig2dev
verify_dependent homebrew/x11/imake
verify_dependent schoeps/homebrew-xfig/transfig
# use github mirror to gnuplot 5.1 (level)
verify_dependent gnuplot --with-qt --with-cairo --universal --HEAD
# icoutils
verify_dependent icoutils
```
I haven't tested the code and don't know if this might result in a difficult to debug problem with home-brew.

**Comment by schoeps** [comment]
I just made a similar modification 20min ago. I call `brew install xxx` without any checks. It does not hurt if the formula is already installed... does this help?

**Comment by bpabbott** [comment]
That should work. I've terminated my current build to verify that `OpenBLAS` builds with Homebrew's `gfortran`. Tomorrow, I'll manually remove a dependent and verify that rerunning the script reinstalls it.

**Comment by schoeps** [comment]
fixed by ac7522f7e7f7d51fa90075fecadfadc30b24eba2

**Comment by bpabbott** [comment]
I removed `gnuplot` and ran the script. I see that `imagemagick` was updated over night, and it being upgraded by the script (which I think is the correct thing to do). When the script completed, `gnuplot` is installed.

**Comment by schoeps** [comment]
Ok, great! 

The script will always use the most recent formulas. I think that makes sense. We could "pin" a specific version if necessary. 

The case of Gnuplot is special. We install the most recent version from the devel branch. However, once installed, there is no easy way to determine if the repository has changed. If desired, we could always uninstall and reinstall gnuplot....
